version: '2'
services:
    web:
        build: .
        working_dir: /var/www/html
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html:rw
        links:
            - db
        environment:
            - FORK_DEBUG=1
            - FORK_ENV=dev

    db:
        image: mariadb
        restart: always
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=fork_cms
            - MYSQL_USER=fork_cms_user
            - MYSQL_PASSWORD=fork_cms_password
            - MYSQL_ROOT_PASSWORD=fork_cms_root
        volumes:
            - ./data/db/databases:/var/lib/mysql:rw
